# Generated by Django 5.0.3 on 2024-03-31 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='modelAkter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='modelDirektor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='modelGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='modelPodpiska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prise', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='modelOtziv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.ForeignKey(default='user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='modelKino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.FilePathField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('file', models.URLField(blank=True, null=True)),
                ('acter', models.ManyToManyField(to='kinopoisk.modelakter')),
                ('direktor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinopoisk.modeldirektor')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinopoisk.modelgenre')),
                ('otziv', models.ManyToManyField(to='kinopoisk.modelotziv')),
                ('podpiska', models.ManyToManyField(to='kinopoisk.modelpodpiska')),
            ],
        ),
    ]
