# Generated by Django 5.0.3 on 2024-04-13 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelakter',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='fotoAkter/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='modeldirektor',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='fotoDirector/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='modelakter',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='modelakter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Актер'),
        ),
        migrations.AlterField(
            model_name='modeldirektor',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='modeldirektor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Режисер'),
        ),
        migrations.AlterField(
            model_name='modelgenre',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='acter',
            field=models.ManyToManyField(to='kinopoisk.modelakter', verbose_name='Актеры'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='country',
            field=models.CharField(max_length=20, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='direktor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinopoisk.modeldirektor', verbose_name='Режисер'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='file',
            field=models.URLField(blank=True, null=True, verbose_name='Трейлер'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kinopoisk.modelgenre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='podpiska',
            field=models.ManyToManyField(to='kinopoisk.modelpodpiska', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='poster/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='modelkino',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='modelotziv',
            name='text',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='modelotziv',
            name='user',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='modelpodpiska',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='modelpodpiska',
            name='prise',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
    ]
