# Generated by Django 5.0.3 on 2024-04-23 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk', '0002_modelakter_foto_modeldirektor_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelkino',
            name='podpiska',
        ),
        migrations.AddField(
            model_name='modelkino',
            name='podpiska',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='kinopoisk.modelpodpiska', verbose_name='Подписка'),
        ),
    ]
